import { randomUUID } from "node:crypto";
import "dotenv/config";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { eq, sql } from "drizzle-orm";
import { getPgClient } from "@scrimspec/db";
import { db } from "@/shared/lib/db";
import { contentFormatChannels, contentFormatEvidence, contentFormatVideos, contentFormats, discoveryClusters, discoveryRuns, nicheQueries, niches, videoDiscoveries, youtubeChannels, youtubeVideos } from "@/shared/lib/schema";
import { ContentFormatConflictError, archiveContentFormat, attachChannelToContentFormat, attachVideoToContentFormat, bulkAttachVideosToContentFormat, createContentFormat, createContentFormatEvidence, detachVideoFromContentFormat, getContentFormatDetail, listContentFormats, restoreContentFormat, updateContentFormat, updateVideoAssociation } from "./content-formats";

const created: { formats: string[]; videos: string[]; channels: string[]; runs: string[]; niches: string[] } = { formats: [], videos: [], channels: [], runs: [], niches: [] };
const uid = () => randomUUID();
async function fixture() { const id = uid(); const [{ id: nicheId }] = await db.insert(niches).values({ name: `cf niche ${id}`, slug: `cf-niche-${id}`, updatedAt: new Date().toISOString() }).returning({ id: niches.id }); created.niches.push(nicheId); const [{ id: queryId }] = await db.insert(nicheQueries).values({ nicheId, query: `cf query ${id}` }).returning({ id: nicheQueries.id }); const [{ id: runId }] = await db.insert(discoveryRuns).values({ nicheId, status: "completed", searchOrders: ["relevance"], totalSteps: 0, requestBudget: 10, updatedAt: new Date().toISOString() }).returning({ id: discoveryRuns.id }); created.runs.push(runId); const channels = await db.insert(youtubeChannels).values(["a","b","c"].map(x => ({ youtubeChannelId: `cf-${x}-${id}`, title: `CF ${x}` }))).returning({ id: youtubeChannels.id }); created.channels.push(...channels.map(x => x.id)); const videos = await db.insert(youtubeVideos).values([0,1,2,3].map(i => ({ youtubeId: `cf-video-${i}-${id}`, url: `https://test/${id}/${i}`, title: `Format ${i}`, channelId: channels[i % 2].id }))).returning({ id: youtubeVideos.id }); created.videos.push(...videos.map(x => x.id)); await db.insert(videoDiscoveries).values(videos.slice(0,2).map((v,i) => ({ runId, videoId: v.id, queryId, searchOrder: "relevance", resultPosition: i + 1 }))); return { runId, channels: channels.map(x => x.id), videos: videos.map(x => x.id) }; }
async function format(name = `Format ${uid()}`) { const row = await createContentFormat({ name }); created.formats.push(row.id); return row; }
afterEach(async () => { for (const id of created.formats.splice(0)) await db.delete(contentFormats).where(eq(contentFormats.id, id)); for (const id of created.runs.splice(0)) await db.delete(discoveryRuns).where(eq(discoveryRuns.id,id)); for (const id of created.videos.splice(0)) await db.delete(youtubeVideos).where(eq(youtubeVideos.id,id)); for (const id of created.channels.splice(0)) await db.delete(youtubeChannels).where(eq(youtubeChannels.id,id)); for (const id of created.niches.splice(0)) await db.delete(niches).where(eq(niches.id,id)); }); afterAll(async()=>{ await getPgClient().end(); });

describe("content formats DB integration", () => {
 it("creates collision-safe slugs, lists bounded rows, updates without slug mutation, and archives/restores", async () => { const a=await format("Economics of Owning X"); const b=await format("Economics of Owning X"); expect(a.slug).toBe("economics-of-owning-x"); expect(b.slug).toBe("economics-of-owning-x-2"); const before=a.updatedAt; const updated=await updateContentFormat(a.id,{name:"Renamed",hookPattern:"Hook",targetDurationMinSeconds:30,targetDurationMaxSeconds:30}); expect(updated.slug).toBe(a.slug); expect(updated.hookPattern).toBe("Hook"); expect(updated.updatedAt).not.toBe(before); expect((await listContentFormats({search:"renamed",limit:"1"})).length).toBe(1); await archiveContentFormat(a.id); expect((await listContentFormats()).some(x=>x.format.id===a.id)).toBe(false); expect((await listContentFormats({status:"archived"})).some(x=>x.format.id===a.id)).toBe(true); expect((await restoreContentFormat(a.id)).status).toBe("draft"); });
 it("enforces duration constraint in Zod and database", async () => { await expect(async()=>createContentFormat({name:"bad",targetDurationMinSeconds:2,targetDurationMaxSeconds:1})).rejects.toThrow(); await expect(async()=>db.execute(sql`insert into content_formats(name,slug,target_duration_min_seconds,target_duration_max_seconds) values ('bad','bad-${uid()}',2,1)`)).rejects.toThrow(); });
 it("attaches, idempotently updates and detaches videos without deleting source video", async () => { const f=await format(); const x=await fixture(); await attachVideoToContentFormat(f.id,{videoId:x.videos[0],role:"supporting"}); await attachVideoToContentFormat(f.id,{videoId:x.videos[0],role:"supporting"}); expect((await db.select().from(contentFormatVideos).where(eq(contentFormatVideos.contentFormatId,f.id))).length).toBe(1); await updateVideoAssociation(f.id,x.videos[0],{role:"exemplar",confidence:.8,note:"strong"}); expect((await getContentFormatDetail(f.id)).counts.exemplarVideoCount).toBe(1); await detachVideoFromContentFormat(f.id,x.videos[0]); expect((await db.select().from(youtubeVideos).where(eq(youtubeVideos.id,x.videos[0]))).length).toBe(1); });
 it("bulk attaches Discovery videos atomically and idempotently", async () => { const f=await format(); const x=await fixture(); const payload={videoIds:[x.videos[0],x.videos[0],x.videos[1]],role:"supporting" as const,source:"discovery" as const,discoveryRunId:x.runId}; await bulkAttachVideosToContentFormat(f.id,payload); await bulkAttachVideosToContentFormat(f.id,payload); expect((await db.select().from(contentFormatVideos).where(eq(contentFormatVideos.contentFormatId,f.id))).length).toBe(2); const failed=await format(); await expect(bulkAttachVideosToContentFormat(failed.id,{...payload,videoIds:[x.videos[0],x.videos[2]]})).rejects.toBeInstanceOf(ContentFormatConflictError); expect((await db.select().from(contentFormatVideos).where(eq(contentFormatVideos.contentFormatId,failed.id))).length).toBe(0); });
 it("keeps channel links manual and returns accurate detail counts", async () => { const f=await format(); const x=await fixture(); for (const [i,v] of x.videos.slice(0,3).entries()) await attachVideoToContentFormat(f.id,{videoId:v,role:i<2?"exemplar":"supporting"}); await attachChannelToContentFormat(f.id,{channelId:x.channels[0],role:"primary"}); await attachChannelToContentFormat(f.id,{channelId:x.channels[1],role:"frequent"}); for(const v of x.videos.slice(0,3)) await createContentFormatEvidence(f.id,{videoId:v,evidenceType:"title_pattern",statement:`Evidence ${v}`}); await createContentFormatEvidence(f.id,{channelId:x.channels[0],evidenceType:"other",statement:"Channel evidence"}); const d=await getContentFormatDetail(f.id,{limit:"2"}); expect(d.counts).toMatchObject({videoCount:3,exemplarVideoCount:2,channelCount:2,evidenceCount:4}); expect(d.videos).toHaveLength(2); expect(d.evidence).toHaveLength(2); expect((await db.select().from(contentFormatChannels).where(eq(contentFormatChannels.contentFormatId,f.id))).length).toBe(2); });
 it("validates and preserves evidence, including Discovery-only provenance", async () => { const f=await format(); const x=await fixture(); const e=await createContentFormatEvidence(f.id,{videoId:x.videos[0],evidenceType:"hook",statement:"Opens with surprise"}); expect(e.videoId).toBe(x.videos[0]); const p=await createContentFormatEvidence(f.id,{evidenceType:"other",statement:"Discovery observation",provenance:{discoveryRunId:x.runId,sourceField:"title"}}); expect(p.provenance).toMatchObject({discoveryRunId:x.runId}); await expect(createContentFormatEvidence(f.id,{evidenceType:"other",statement:"bad",provenance:{discoveryRunId:uid()}})).rejects.toBeInstanceOf(ContentFormatConflictError); await expect(createContentFormatEvidence(f.id,{evidenceType:"other",statement:"bad",provenance:{secret:"x"}})).rejects.toThrow(); await archiveContentFormat(f.id); await expect(createContentFormatEvidence(f.id,{videoId:x.videos[0],evidenceType:"other",statement:"blocked"})).rejects.toBeInstanceOf(ContentFormatConflictError); expect((await db.select().from(contentFormatEvidence).where(eq(contentFormatEvidence.id,e.id))).length).toBe(1); });
 it("does not mix computed Discovery cluster labels with central formats", async () => { const f=await format("Central Format"); const x=await fixture(); const [{id: clusterId}]=await db.insert(discoveryClusters).values({runId:x.runId,label:"L",summary:"S",researchScore:"0",adjustedResearchScore:"0",labelQualityScore:"0",dominantLanguage:"en",languageMatchScore:"0",contentFormat:"Computed Label",audience:"A",suggestedQueries:[],whyResearchable:"W",semanticCohesion:"0",repeatedFormatEvidence:"0",isOutlier:false,videoCount:0,channelCount:0,medianViewsPerDay:"0",smallChannelCount:0,representativeTitles:[]}).returning({id:discoveryClusters.id}); const [cluster]=await db.select().from(discoveryClusters).where(eq(discoveryClusters.id,clusterId)); expect(cluster.contentFormat).toBe("Computed Label"); expect((await getContentFormatDetail(f.id)).format.name).toBe("Central Format"); });
});
